title: Fertig Lab
description: A website for Fertig Lab Onboarding and Information
theme: just-the-docs
# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: FertigLabFavicon.png

url: https://juliambowden.github.io/vigilant-fishstick

exclude:
 # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
 # specific to the theme website:
   - bin/
   - lib/
   - "*.gemspec"
   - "*.gem"
   - LICENSE.txt
   - package.json
   - package-lock.json
   - Rakefile
   - README.md
 # theme test code
   - fixtures/
