title: Fertig Lab
description: A website for Fertig Lab's Onboarding and Information
theme: just-the-docs

url: https://juliambowden.github.io/vigilant-fishstick

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
